# test_stemmer.py
# generated by Deepseek AI for convenience
# Usage: run "python -m pytest tests/porter_tests.py -v" from search_engine directory

import pytest
from core.stemmer import (
    porter_transform,
    step_1a,
    step_1b,
    step_1c,
    step_2,
    step_3,
    step_4,
    step_5a,
    step_5b,
    m_value,
    contains_vowel,
    star_o,
    stem_tokens
)


class TestHelperFunctions:
    """Test the helper functions used by the stemmer."""
    
    def test_contains_vowel(self):
        """Test contains_vowel function."""
        assert contains_vowel("sky") is True      # y after consonant
        assert contains_vowel("by") is True       # y after consonant
        assert contains_vowel("fly") is True      # y after consonant
        assert contains_vowel("play") is True     # has 'a' and y
        assert contains_vowel("myth") is True     # y after consonant
        assert contains_vowel("rhythm") is True   # y after consonant
        assert contains_vowel("psst") is False    # no vowels
        assert contains_vowel("crypt") is True    # y after consonant
        assert contains_vowel("tsktsk") is False  # no vowels
    
    def test_m_value(self):
        """Test m_value calculation."""
        # Words with m=0
        assert m_value("sky") == 0       # C V
        assert m_value("by") == 0        # C V
        assert m_value("tree") == 0      # C C V V
        assert m_value("f") == 0         # C
        
        # Words with m=1
        assert m_value("play") == 1      # C C V C
        assert m_value("yes") == 1       # C V C
        assert m_value("happy") == 1     # C V C C V
        assert m_value("agr") == 1       # V C C
        assert m_value("trouble") == 1   # C V C V

        # Words with m=2
        assert m_value("syzygy") == 2    # C V C V C V
        
        # Words with m=3
        assert m_value("beautiful") == 3 # C V C V C V C
        
        # Edge cases
        assert m_value("") == 0
        assert m_value("a") == 0
        assert m_value("ab") == 1        # V C 
    
    def test_star_o(self):
        """Test star_o function."""
        # Words ending in CVC where last C is not W, X, Y
        assert star_o("hop") is True     # h-o-p (C-V-C, p not w/x/y)
        assert star_o("wil") is True     # w-i-l (C-V-C, l not w/x/y)
        assert star_o("vet") is True     # v-e-t (C-V-C, t not w/x/y)
        
        # Words ending in CVC where last C is W, X, or Y
        assert star_o("low") is False    # l-o-w (w is invalid)
        assert star_o("tax") is False    # t-a-x (x is invalid)
        assert star_o("say") is False    # s-a-y (y is invalid)
        
        # Words not ending in CVC
        assert star_o("hoping") is False # too long
        assert star_o("at") is False     # too short
        assert star_o("") is False       # empty
        assert star_o("ab") is False     # too short


class TestStep1a:
    """Test Step 1a: Plurals and past participles."""
    
    def test_sses_to_ss(self):
        """SSES -> SS."""
        assert step_1a("caresses") == "caress"
        assert step_1a("presses") == "press"
        assert step_1a("misses") == "miss"
    
    def test_ies_to_i(self):
        """IES -> I."""
        assert step_1a("ponies") == "poni"
        assert step_1a("ties") == "ti"
        assert step_1a("cries") == "cri"
        assert step_1a("flies") == "fli"
    
    def test_ss_unchanged(self):
        """SS -> SS (no change)."""
        assert step_1a("press") == "press"
        assert step_1a("class") == "class"
    
    def test_s_removal(self):
        """S -> (nothing)."""
        assert step_1a("cats") == "cat"
        assert step_1a("dogs") == "dog"
        assert step_1a("cars") == "car"
    
    def test_no_change(self):
        """Words that shouldn't change."""
        assert step_1a("cat") == "cat"
        assert step_1a("dog") == "dog"
        assert step_1a("car") == "car"


class TestStep1b:
    """Test Step 1b: Past participles and progressive forms."""
    
    def test_eed_to_ee(self):
        """(m>0) EED -> EE."""
        assert step_1b("agreed") == "agree"
        
        assert step_1b("bled") == "bled"      # no "eed"
    
    def test_ed_removal(self):
        """(*v*) ED ->."""
        assert step_1b("plastered") == "plaster"
        assert step_1b("motored") == "motor"
        assert step_1b("bled") == "bled"      # no vowel, so no change
        assert step_1b("feed") == "feed"      # common suffix -eed first, condition doesnt match so return original
    
    def test_ing_removal(self):
        """(*v*) ING ->."""
        assert step_1b("motoring") == "motor"
        assert step_1b("running") == "run"    # extra_step handles double consonant
        assert step_1b("sing") == "sing"      # no vowel, so no change
    
    def test_extra_step_at(self):
        """AT -> ATE in extra_step."""
        assert step_1b("conflated") == "conflate"
    
    def test_extra_step_bl(self):
        """BL -> BLE in extra_step."""
        assert step_1b("troubled") == "trouble"
    
    def test_extra_step_iz(self):
        """IZ -> IZE in extra_step."""
        assert step_1b("sized") == "size"
    
    def test_extra_step_double_cons(self):
        """Double consonant removal in extra_step."""
        assert step_1b("hopped") == "hop"
        assert step_1b("tanned") == "tan"
        assert step_1b("falling") == "fall"    # 'll' stays because l is special
        assert step_1b("hissing") == "hiss"    # 'ss' stays because s is special


class TestStep1c:
    """Test Step 1c: Y -> I."""
    
    def test_y_to_i(self):
        """(*v*) Y -> I."""
        assert step_1c("happy") == "happi"
        assert step_1c("sky") == "sky"        # no vowel before y? Actually "sky" has vowel y after consonant
        # Wait, "sky" has y after consonant, so it should change?
        # Let me check: "sky" → s(c) k(c) y(v) → contains_vowel("sk") is False
        # So no change
        assert step_1c("fly") == "fly"        # no vowel before y
        assert step_1c("by") == "by"          # no vowel before y
        assert step_1c("cry") == "cry"        # no vowel before y
        assert step_1c("deny") == "deni"      # "den" has vowel 'e'


class TestStep2:
    """Test Step 2: Suffix transformations."""
    
    def test_ational_to_ate(self):
        """(m>0) ATIONAL -> ATE."""
        assert step_2("relational") == "relate"
        assert step_2("national") == "national" 
        pass
    
    def test_tional_to_tion(self):
        """(m>0) TIONAL -> TION."""
        assert step_2("conditional") == "condition"
    
    def test_enci_to_ence(self):
        """(m>0) ENCI -> ENCE."""
        assert step_2("valenci") == "valence"
    
    def test_anci_to_ance(self):
        """(m>0) ANCI -> ANCE."""
        assert step_2("hesitanci") == "hesitance"
    
    def test_izer_to_ize(self):
        """(m>0) IZER -> IZE."""
        assert step_2("digitizer") == "digitize"
    
    def test_abli_to_able(self):
        """(m>0) ABLI -> ABLE."""
        assert step_2("conformabli") == "conformable"
    
    def test_alli_to_al(self):
        """(m>0) ALLI -> AL."""
        assert step_2("radicalli") == "radical"
    
    def test_entli_to_ent(self):
        """(m>0) ENTLI -> ENT."""
        assert step_2("differentli") == "different"
    
    def test_eli_to_e(self):
        """(m>0) ELI -> E."""
        assert step_2("vileli") == "vile"
    
    def test_ousli_to_ous(self):
        """(m>0) OUSLI -> OUS."""
        assert step_2("analogousli") == "analogous"
    
    def test_ization_to_ize(self):
        """(m>0) IZATION -> IZE."""
        assert step_2("vietnamization") == "vietnamize"
    
    def test_ation_to_ate(self):
        """(m>0) ATION -> ATE."""
        assert step_2("predication") == "predicate"
    
    def test_ator_to_ate(self):
        """(m>0) ATOR -> ATE."""
        assert step_2("operator") == "operate"
    
    def test_alism_to_al(self):
        """(m>0) ALISM -> AL."""
        assert step_2("feudalism") == "feudal"
    
    def test_iveness_to_ive(self):
        """(m>0) IVENESS -> IVE."""
        assert step_2("decisiveness") == "decisive"
    
    def test_fulness_to_ful(self):
        """(m>0) FULNESS -> FUL."""
        assert step_2("hopefulness") == "hopeful"
    
    def test_ousness_to_ous(self):
        """(m>0) OUSNESS -> OUS."""
        assert step_2("callousness") == "callous"
    
    def test_aliti_to_al(self):
        """(m>0) ALITI -> AL."""
        assert step_2("formaliti") == "formal"
    
    def test_iviti_to_ive(self):
        """(m>0) IVITI -> IVE."""
        assert step_2("sensitiviti") == "sensitive"
    
    def test_biliti_to_ble(self):
        """(m>0) BILITI -> BLE."""
        assert step_2("sensibiliti") == "sensible"


class TestStep3:
    """Test Step 3: More suffix transformations."""
    
    def test_icate_to_ic(self):
        """(m>0) ICATE -> IC."""
        assert step_3("triplicate") == "triplic"
    
    def test_ative_removal(self):
        """(m>0) ATIVE ->."""
        assert step_3("formative") == "form"
    
    def test_alize_to_al(self):
        """(m>0) ALIZE -> AL."""
        assert step_3("formalize") == "formal"
    
    def test_iciti_to_ic(self):
        """(m>0) ICITI -> IC."""
        assert step_3("electriciti") == "electric"
    
    def test_ical_to_ic(self):
        """(m>0) ICAL -> IC."""
        assert step_3("electrical") == "electric"
    
    def test_ful_removal(self):
        """(m>0) FUL ->."""
        assert step_3("hopeful") == "hope"
    
    def test_ness_removal(self):
        """(m>0) NESS ->."""
        assert step_3("goodness") == "good"


class TestStep4:
    """Test Step 4: Remove suffixes."""
    
    def test_al_removal(self):
        """(m>1) AL ->."""
        assert step_4("revival") == "reviv"
    
    def test_ance_removal(self):
        """(m>1) ANCE ->."""
        assert step_4("allowance") == "allow"
    
    def test_ence_removal(self):
        """(m>1) ENCE ->."""
        assert step_4("inference") == "infer"
    
    def test_er_removal(self):
        """(m>1) ER ->."""
        assert step_4("airliner") == "airlin"
    
    def test_ic_removal(self):
        """(m>1) IC ->."""
        assert step_4("gyroscopic") == "gyroscop"
    
    def test_able_removal(self):
        """(m>1) ABLE ->."""
        assert step_4("adjustable") == "adjust"
    
    def test_ible_removal(self):
        """(m>1) IBLE ->."""
        assert step_4("defensible") == "defens"
    
    def test_ant_removal(self):
        """(m>1) ANT ->."""
        assert step_4("irritant") == "irrit"
    
    def test_ement_removal(self):
        """(m>1) EMENT ->."""
        assert step_4("replacement") == "replac"
    
    def test_ment_removal(self):
        """(m>1) MENT ->."""
        assert step_4("adjustment") == "adjust"
    
    def test_ent_removal(self):
        """(m>1) ENT ->."""
        assert step_4("dependent") == "depend"
    
    def test_ion_removal_with_s(self):
        """(m>1 and *S) ION ->."""
        assert step_4("adoption") == "adopt"  # stem ends with 't'
        assert step_4("adhesion") == "adhes"  # stem ends with 's'? Actually "adhes" has 's'
        # "adhesion" → "adhes" (ion removed)
    
    def test_ou_removal(self):
        """(m>1) OU ->."""
        assert step_4("homologou") == "homolog"
    
    def test_ism_removal(self):
        """(m>1) ISM ->."""
        assert step_4("communism") == "commun"
    
    def test_ate_removal(self):
        """(m>1) ATE ->."""
        assert step_4("activate") == "activ"
    
    def test_iti_removal(self):
        """(m>1) ITI ->."""
        assert step_4("angulariti") == "angular"
    
    def test_ous_removal(self):
        """(m>1) OUS ->."""
        assert step_4("homologous") == "homolog"
    
    def test_ive_removal(self):
        """(m>1) IVE ->."""
        assert step_4("effective") == "effect"
    
    def test_ize_removal(self):
        """(m>1) IZE ->."""
        assert step_4("bowdlerize") == "bowdler"


class TestStep5:
    """Test Steps 5a and 5b: Tidying up."""
    
    def test_step5a_m_gt_1(self):
        """(m>1) E ->."""
        assert step_5a("probate") == "probat"
        assert step_5a("rate") == "rate"  # m=1, not *o, so no change
        assert step_5a("cease") == "ceas" # m=1, not *o? Actually "cea" has m=1, not *o → remove e
    
    def test_step5a_m_eq_1_not_star_o(self):
        """(m=1 and not *o) E ->."""
        assert step_5a("cease") == "ceas"
        # "cease" → stem "cea" → m=1, not *o → remove e
    
    def test_step5a_no_change(self):
        """Words that shouldn't change."""
        assert step_5a("rate") == "rate"   # m=1 and *o? "rat" = CVC, last char t not w/x/y → *o is True
        # Actually "rate" → stem "rat" → m=1, *o=True → don't remove e
    
    def test_step5b_double_consonant(self):
        """(m > 1 and *d and *L) -> single letter."""
        assert step_5b("controll") == "control"
        assert step_5b("roll") == "roll"   # m=1, so no change
        assert step_5b("stroll") == "stroll" # m=1? Actually "stroll" has m=1? No, "stroll" = s-t-r-o-l-l → C-C-C-V-C-C → m=1
        # So no change


class TestFullStemmer:
    """Test the complete Porter Stemmer with real words."""
    
    def test_common_words(self):
        """Test common English words."""
        test_cases = [
            ("running", "run"),
            ("ran", "ran"),
            ("runs", "run"),
            ("cats", "cat"),
            ("caresses", "caress"),
            ("ponies", "poni"),
            ("trouble", "troubl"),
            ("troubled", "troubl"),
            ("troubling", "troubl"),
            ("agreed", "agre"),
            ("agreement", "agreement"),
            ("happiness", "happi"),
            ("beautiful", "beauti"),
            ("effective", "effect"),
            ("national", "nation"),  # Wait, this should be "nation" not "nat"
            # Let me verify: "national" → "nation" 
        ]
        
        for word, expected in test_cases:
            result = porter_transform(word)
            assert result == expected, f"'{word}' → '{result}' (expected '{expected}')"
    
    def test_stem_tokens(self):
        """Test stemming a list of tokens."""
        tokens = ["running", "ran", "runs", "runner"]
        result = stem_tokens(tokens)
        
        # All should stem to "run"
        expected = ["run", "ran", "run", "runner"]
        assert sorted(result[0]) == sorted(expected)
    
    def test_stem_tokens_with_duplicates(self):
        """Test that duplicates are removed."""
        tokens = ["cat", "cat", "cats", "cat"]
        result = stem_tokens(tokens)
        expected = ["cat"]
        assert sorted(result[1]) == sorted(expected)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])